-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "accounts"."Accounts" add column "verified" boolean
--  not null default 'false';
